from . import help
from . import start
from . import savatcha
from . import menu
from . import baliq
from . import shashlik
from . import zakuska
from . import salats
from . import suv
from . import shurva
from . import orqaga
from . import miqdor
from . import narxi
from . import buyurtma
from . import delete_pro
from . import admin
